---
label: Recipe
hide_body: false
fields:
- type: text
  name: title
  label: title
  config:
    required: true
  description: Capitalize first word
- type: datetime
  name: date
  label: date
  config:
    required: true
  default: now
- type: text
  name: source
  label: source
- type: number
  name: serves
  label: serves
  config:
    required: true
  default: 2
- type: file
  name: image
  label: image
- type: text
  name: slug
  label: slug
  description: same as title, lower-case, words delimited with hyphen
  config:
    required: true
- name: description
  type: textarea
  default: ''
  config:
    required: true
    wysiwyg: false
    schema:
      format: markdown
    min: 10
    max: 256
  label: description
  description: Add a short description
- name: author
  type: select
  default: rick
  config:
    required: false
    options:
    - Rick
    - Rose
    source:
      type: simple
      section: 
      file: 
      path: 
  label: author
pages:
- recipes/italian/alfredo-s-alfredo.md
- recipes/italian/carbonara.md
- recipes/other/shrimp-in-lime-and-garlic.md
- recipes/tips/on-quantities.md
